# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyAppleContainer < Formula
  desc "A simple terminal UI for Apple Container, written in Go"
  homepage "https://github.com/g-battaglia/lazy-apple-container/"
  version "0.1.0"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/g-battaglia/lazy-apple-container/releases/download/v0.1.0/lazy-apple-container_0.1.0_Darwin_arm64.tar.gz"
    sha256 "cdf3af8002c6f14abafdba4601291012b9fd3cc29898e13ead9f30f8e84a6a4e"

    define_method(:install) do
      bin.install "lazyapple"
    end
  end
end
