# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class LazyAppleContainer < Formula
  desc "A simple terminal UI for Apple Container, written in Go"
  homepage "https://github.com/g-battaglia/lazy-apple-container/"
  version "1.0.1"
  depends_on :macos

  if Hardware::CPU.arm?
    url "https://github.com/g-battaglia/lazy-apple-container/releases/download/v1.0.1/lazy-apple-container_1.0.1_Darwin_arm64.tar.gz"
    sha256 "93cbbdad150b7c137f9240ab6474d83861694009df23565189d9f9897ed975c2"

    define_method(:install) do
      bin.install "lazyapple"
    end
  end
end
